
title: Cristian Sulea
description: >- # this means to ignore newlines until next key
  Software Developer

author:
  name: Cristian Sulea
  url: https://cristian.sulea.net

url: "http://cristian-sulea.github.io" # the base hostname & protocol, e.g. http://example.com
baseurl: "" # the subpath, e.g. /blog

copyright: >- # this means to ignore newlines until next key
  © 2024 <a href=\"https://cristian.sulea.net\">Cristian Sulea</a>.
  Powered by <a href="https://jekyllrb.com">Jekyll</a>
  and <a href="https://github.com/cristian-sulea/jekyll-theme-pwkbb">pwkbb</a>.

social:
  links:
    - { platform: linkedin, title: LinkedIn, link: "https://www.linkedin.com/in/cristiansulea" }
    - { platform: github,   title: GitHub,   link: "https://github.com/cristian-sulea" }
    - { platform: twitter,  title: Twitter,  link: "https://twitter.com/cristian_sulea" }

date:
  format: "%b %-d, %Y"

#theme: minima
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

###

collections_dir: content

collections:
  blog:
    output: true
    sort_by: date
    permalink: /blog/:name
  #projects:
  #  output: true
  #  #sort_by: path

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"

#defaults:
#  - scope:
#      path: ""
#      type: "projects"
#    values:
#      layout: "index"
#      author: "Cristian Sulea"
#      permalink: /:collection/:name
#  - scope:
#      path: "_blog/xyz"
#      type: "blog"
#    values:
#      layout: "index"
#      author: "Cri Sul"
#  - scope:
#      path: ""
#    values:
#      layout: "index"